// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TrustManagerSecretTargetsApplyConfiguration represents a declarative configuration of the TrustManagerSecretTargets type for use
// with apply.
type TrustManagerSecretTargetsApplyConfiguration struct {
	Enabled              *bool    `json:"enabled,omitempty"`
	AuthorizedSecretsAll *bool    `json:"authorizedSecretsAll,omitempty"`
	AuthorizedSecrets    []string `json:"authorizedSecrets,omitempty"`
}

// TrustManagerSecretTargetsApplyConfiguration constructs a declarative configuration of the TrustManagerSecretTargets type for use with
// apply.
func TrustManagerSecretTargets() *TrustManagerSecretTargetsApplyConfiguration {
	return &TrustManagerSecretTargetsApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *TrustManagerSecretTargetsApplyConfiguration) WithEnabled(value bool) *TrustManagerSecretTargetsApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithAuthorizedSecretsAll sets the AuthorizedSecretsAll field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthorizedSecretsAll field is set to the value of the last call.
func (b *TrustManagerSecretTargetsApplyConfiguration) WithAuthorizedSecretsAll(value bool) *TrustManagerSecretTargetsApplyConfiguration {
	b.AuthorizedSecretsAll = &value
	return b
}

// WithAuthorizedSecrets adds the given value to the AuthorizedSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AuthorizedSecrets field.
func (b *TrustManagerSecretTargetsApplyConfiguration) WithAuthorizedSecrets(values ...string) *TrustManagerSecretTargetsApplyConfiguration {
	for i := range values {
		b.AuthorizedSecrets = append(b.AuthorizedSecrets, values[i])
	}
	return b
}
