// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
)

// TrustManagerSpecApplyConfiguration represents a declarative configuration of the TrustManagerSpec type for use
// with apply.
type TrustManagerSpecApplyConfiguration struct {
	ManagementState           *operatorv1alpha1.Mode                                   `json:"managementState,omitempty"`
	LogLevel                  *int32                                                   `json:"logLevel,omitempty"`
	LogFormat                 *string                                                  `json:"logFormat,omitempty"`
	TrustNamespace            *string                                                  `json:"trustNamespace,omitempty"`
	SecretTargets             *TrustManagerSecretTargetsApplyConfiguration             `json:"secretTargets,omitempty"`
	FilterExpiredCertificates *TrustManagerFilterExpiredCertificatesApplyConfiguration `json:"filterExpiredCertificates,omitempty"`
	ControllerConfig          *TrustManagerControllerConfigApplyConfiguration          `json:"controllerConfig,omitempty"`
}

// TrustManagerSpecApplyConfiguration constructs a declarative configuration of the TrustManagerSpec type for use with
// apply.
func TrustManagerSpec() *TrustManagerSpecApplyConfiguration {
	return &TrustManagerSpecApplyConfiguration{}
}

// WithManagementState sets the ManagementState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementState field is set to the value of the last call.
func (b *TrustManagerSpecApplyConfiguration) WithManagementState(value operatorv1alpha1.Mode) *TrustManagerSpecApplyConfiguration {
	b.ManagementState = &value
	return b
}

// WithLogLevel sets the LogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogLevel field is set to the value of the last call.
func (b *TrustManagerSpecApplyConfiguration) WithLogLevel(value int32) *TrustManagerSpecApplyConfiguration {
	b.LogLevel = &value
	return b
}

// WithLogFormat sets the LogFormat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogFormat field is set to the value of the last call.
func (b *TrustManagerSpecApplyConfiguration) WithLogFormat(value string) *TrustManagerSpecApplyConfiguration {
	b.LogFormat = &value
	return b
}

// WithTrustNamespace sets the TrustNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrustNamespace field is set to the value of the last call.
func (b *TrustManagerSpecApplyConfiguration) WithTrustNamespace(value string) *TrustManagerSpecApplyConfiguration {
	b.TrustNamespace = &value
	return b
}

// WithSecretTargets sets the SecretTargets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretTargets field is set to the value of the last call.
func (b *TrustManagerSpecApplyConfiguration) WithSecretTargets(value *TrustManagerSecretTargetsApplyConfiguration) *TrustManagerSpecApplyConfiguration {
	b.SecretTargets = value
	return b
}

// WithFilterExpiredCertificates sets the FilterExpiredCertificates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FilterExpiredCertificates field is set to the value of the last call.
func (b *TrustManagerSpecApplyConfiguration) WithFilterExpiredCertificates(value *TrustManagerFilterExpiredCertificatesApplyConfiguration) *TrustManagerSpecApplyConfiguration {
	b.FilterExpiredCertificates = value
	return b
}

// WithControllerConfig sets the ControllerConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControllerConfig field is set to the value of the last call.
func (b *TrustManagerSpecApplyConfiguration) WithControllerConfig(value *TrustManagerControllerConfigApplyConfiguration) *TrustManagerSpecApplyConfiguration {
	b.ControllerConfig = value
	return b
}
