// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TrustManagerFilterExpiredCertificatesApplyConfiguration represents a declarative configuration of the TrustManagerFilterExpiredCertificates type for use
// with apply.
type TrustManagerFilterExpiredCertificatesApplyConfiguration struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// TrustManagerFilterExpiredCertificatesApplyConfiguration constructs a declarative configuration of the TrustManagerFilterExpiredCertificates type for use with
// apply.
func TrustManagerFilterExpiredCertificates() *TrustManagerFilterExpiredCertificatesApplyConfiguration {
	return &TrustManagerFilterExpiredCertificatesApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *TrustManagerFilterExpiredCertificatesApplyConfiguration) WithEnabled(value bool) *TrustManagerFilterExpiredCertificatesApplyConfiguration {
	b.Enabled = &value
	return b
}
